name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  # This workflow contains a single job called "publishToGallery"
  checkFileLocations:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      #copy files
    - name: Check
      shell: pwsh
      run: |
        write-host "Checking repo structure: $env:GITHUB_WORKSPACE"
        dir "$env:GITHUB_WORKSPACE"
        
