name: CI
on:
  push:
    branches:
      - master
    paths:
      - '**.psd1'
      - '**.psm1'
      - '**.ps1'
    tags:
      - 'v*'


jobs:
  checkoutCode:
    runs-on: windows-latest
    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      #copy files
    - name: Build
      shell: pwsh
      run: |
        write-host "Building in: $env:GITHUB_WORKSPACE\S.DS.P"
        New-Item -Path  "$env:GITHUB_WORKSPACE" -Name S.DS.P -ItemType Directory -Force | Out-Null
        Copy-Item -Path "$env:GITHUB_WORKSPACE\S.DS.P.psd1" -Destination "$env:GITHUB_WORKSPACE\S.DS.P\" -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE\S.DS.P.psm1" -Destination "$env:GITHUB_WORKSPACE\S.DS.P\" -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE\LICENSE.TXT" -Destination "$env:GITHUB_WORKSPACE\S.DS.P\" -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE\Transforms\" -Destination "$env:GITHUB_WORKSPACE\S.DS.P\" -Recurse -Force 

  # This workflow contains a single job called "publishToGallery"
  publishToGallery:
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: checkoutCode
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Publish
      shell: pwsh
      env:
        SECRET: ${{ secrets.PSGallery_APIKey }}
      run: |
        write-host "Publishing from: $env:GITHUB_WORKSPACE\S.DS.P"
        try
        {
          Publish-Module -Path "$env:GITHUB_WORKSPACE\S.DS.P" -NuGetApiKey "$env:SECRET"
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }
  createRelease:
    runs-on: windows-latest
    needs: checkoutCode
    steps:
    - name: Install 7Zip PowerShell Module
      shell: pwsh
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Compress
      shell: pwsh
      run: |
        write-host "Compressing: $env:GITHUB_WORKSPACE\S.DS.P"
        try
        {
            Compress-7Zip -Format Zip -Path "$env:GITHUB_WORKSPACE\S.DS.P" -ArchiveFileName .\s.ds.p.zip
            write-host "Compression done"
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }
    - name: CreateRelease
      uses: actions/create-release@latest
      with:
        artifacts: ".\s.ds.p.zip"
        token: ${{ secrets.GITHUB_TOKEN }}



